------------------------------------------------------------------------------------
--
-- Filename: recipes_schema_2.sql
--
-- Since: Fri Oct 20 01:11:52 CEST 2017
--
-- This file was generated by Kripton Annotation Processor v. 3.0.0
--
------------------------------------------------------------------------------------

CREATE TABLE recipes (id INTEGER PRIMARY KEY AUTOINCREMENT, creation_time TEXT, name TEXT, author_id INTEGER, FOREIGN KEY(author_id) REFERENCES authors(id));
CREATE TABLE ingredients (id INTEGER PRIMARY KEY AUTOINCREMENT, creation_time TEXT, description TEXT, quantity INTEGER, recipe_id INTEGER, FOREIGN KEY(recipe_id) REFERENCES recipes(id));
CREATE TABLE authors (id INTEGER PRIMARY KEY AUTOINCREMENT, creation_time TEXT, name TEXT NOT NULL, surname TEXT NOT NULL, email TEXT NOT NULL); CREATE UNIQUE INDEX idx_authors_0 on authors (name, surname asc); CREATE UNIQUE INDEX idx_authors_1 on authors (email);
