------------------------------------------------------------------------------------
--
-- Filename: recipes_schema_1.sql
--
-- Since: Fri Sep 01 02:07:31 CEST 2017
--
-- This file was generated by Kripton Annotation Processor v2.0.1
--
------------------------------------------------------------------------------------

CREATE TABLE recipes (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, ingredients BLOB);
