------------------------------------------------------------------------------------
--
-- Filename: recipes_schema_1.sql
--
-- Since: Fri Oct 20 01:11:51 CEST 2017
--
-- This file was generated by Kripton Annotation Processor v. 3.0.0
--
------------------------------------------------------------------------------------

CREATE TABLE recipes (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, ingredients BLOB);
