------------------------------------------------------------------------------------
--
-- Filename: students_schema_1.sql
--
-- Since: Fri Sep 01 02:07:30 CEST 2017
--
-- This file was generated by Kripton Annotation Processor v2.0.1
--
------------------------------------------------------------------------------------

CREATE TABLE student (name TEXT, id INTEGER PRIMARY KEY AUTOINCREMENT);
